### ISSUE TITLE
comparison in length is continuing when it should fail

### ISSUE THREAD

**Issue by ghost** [rendonc/python_test#7]
```def dataCompare(prev,new):
  len1=len(prev)
  len2=len(new)
  
  size=0
  if(len1>len2):
    size=len2
  else:
    size=len1
```
if the length of any of the files is different we know they are not the same, there is no real reason to keep on comparing, the function return value is not consistent either, if a difference is detected a tuple is returned while on a failed condition it returns a boolean

**Comment by rendonc** [comment]
The comparison keeps going in order to know the position where the first difference begins.
